# Generated by Django 4.0.1 on 2022-01-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
